- name: Deploy Docker to AWS (EC2) with Custom VPC
  uses: saif-qureos/github-actions-deploy-docker-to-ec2@v0.5.27
  with:
    checkout: true
    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws_default_region: us-east-1
    vpc_id: vpc-0659d2da27b497d1b
    subnet_id: subnet-01d31efead48ea273
    aws_ami_id: ami-0fc5d935ebf8bc3bc
    tf_state_bucket: my-tf-state-bucket
    app_directory: /path/to/your/app
    app_port: 3000
    lb_port: 80
    lb_healthcheck: HTTP:3000
    ec2_instance_profile: your-ec2-instance-profile
    ec2_instance_type: t2.micro
    ec2_volume_size: 10
    aws_create_efs: true
    aws_create_ha_efs: true
    aws_create_efs_replica: true
    aws_enable_efs_backup_policy: true
    aws_efs_zone_mapping: '{"us-east-1a": "all", "us-east-1b": "all"}'
    aws_efs_transition_to_inactive: 30
    aws_replication_configuration_destination: us-east-2
    domain_name: dinnyuy.freedynamicdns.net
    sub_domain: dev
    cert_arn: arn:aws:acm:us-east-1:123456789012:certificate/abcdefgh-1234-5678-90ab-cdef12345678
    create_root_cert: true
    create_sub_cert: true
    stack_destroy: false
    additional_tags: '{"key1": "value1", "key2": "value2"}'
    create_keypair_sm_entry: false
    aws_enable_postgres: true
    aws_postgres_engine: postgres
    aws_postgres_engine_version: 13.4
    aws_postgres_instance_class: db.t2.micro
    aws_postgres_subnets: subnet-0123456789abcdef0,subnet-0123456789abcdef1
    aws_postgres_database_name: mydatabase
    aws_postgres_database_port: 5432
    application_mount_target: my-app-mount
    data_mount_target: /data
    efs_mount_target: /
